# Generated by Django 5.0.7 on 2024-07-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('done', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(related_name='tasks', to='tag.tag')),
            ],
            options={
                'ordering': ('-datetime',),
            },
        ),
    ]
