# Generated by Django 5.0.7 on 2024-07-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-done', '-datetime')},
        ),
    ]
