# Generated by Django 5.0.7 on 2024-07-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('done', '-datetime')},
        ),
    ]
